### ISSUE TITLE
Subject: License Clarification for GPOwned

### ISSUE THREAD

**Issue by zbs54** [X-C3LL/GPOwned#2]
Dear X-C3LL,

I have been reviewing the GPOwned.py project and noticed that the licensing details are not fully clear to me. Could you please clarify the following:

1. What specific license applies to this repository? Is there a LICENSE file or a particular open-source license that this project adheres to?
2. Are there any restrictions or specific conditions under the license that contributors or users should be aware of?
3. If the repository is under a custom license or has dual licensing, could you provide more details on how to comply with the terms?
Your clarification would be greatly appreciated, as I want to ensure proper usage and contribution to this project.

Thank you for your time and support.

Best regards,

**Comment by X-C3LL** [comment]
Hi,

There is no License, you can do with it whatever you want. It's just a crappy & buggy script I uploaded to GitHub 3 years ago. 

Regards.

**Comment by zbs54** [comment]
thx :)
